import { createGameBridge } from "/dist/index.js";
const $ = (id) => document.getElementById(id);
const parentOrigin = new URLSearchParams(location.search).get("parentOrigin");
const bridge = createGameBridge({ gameId: "mock-game", parentOrigin });
const refresh = () => { $("state").textContent = bridge.state; $("session").textContent = bridge.sessionId || "—"; };
const sent = (text) => { $("sent").textContent = text; refresh(); };
bridge.onInitialize((m) => { $("received").textContent = JSON.stringify(m); $("reaction").textContent = "INITIALIZE received"; refresh(); });
bridge.onStart(() => { $("received").textContent = "START"; $("reaction").textContent = "START received"; refresh(); });
bridge.onPause(() => { $("received").textContent = "PAUSE"; $("reaction").textContent = "PAUSE received"; refresh(); });
bridge.onResume(() => { $("received").textContent = "RESUME"; $("reaction").textContent = "RESUME received"; refresh(); });
bridge.onRestart(() => { $("received").textContent = "RESTART"; $("reaction").textContent = "RESTART received"; refresh(); });
bridge.onSetVolume((v) => { $("received").textContent = `SET VOLUME ${v}`; $("reaction").textContent = `Volume ${v}`; refresh(); });
$("ready").onclick = async () => { sent("whs.game.ready"); try { await bridge.ready(); } catch (e) { $("reaction").textContent = e.message; } refresh(); };
$("started").onclick = () => { bridge.started(); sent("whs.game.started"); };
$("checkpoint").onclick = () => { bridge.checkpoint({ checkpoint: "wave-2" }); sent("whs.game.checkpoint"); };
$("complete").onclick = () => { bridge.completed({ score: 1250 }); sent("whs.game.completed"); };
$("fail").onclick = () => { bridge.failed({ reason: "player-defeated" }); sent("whs.game.failed"); };
$("error").onclick = () => { bridge.error({ message: "mock error", code: "MOCK" }); sent("whs.game.error"); };
refresh();
